/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../public/chessKing.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ChessKing(props) {
  const { nodes, materials } = useGLTF("./chessKing.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.001"]}
        position={[0, 1, 0]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[0, 4.592, 0]}
        scale={0.198}
      />
    </group>
  );
}

useGLTF.preload("/chessKing.glb");

export default ChessKing;
